targets:
    $default:
      builders:
        json_serializable:
          options:
            create_to_json: false
        source_gen|combining_builder:
          options:
            ignore_for_file:
              - implicit_dynamic_parameter
              - unused_element